version: "3.8"

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    extra_hosts:
      - host.docker.internal:172.17.0.1
    depends_on:
      - db 
   # command: ["sh", "-c", "wait-for-it db:27017 -- npm run start"]

  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root 
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 

volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    driver: bridge